### ISSUE TITLE
Error using createBackupConfiguration

### ISSUE THREAD

**Issue by masterix21** [laravel/forge-sdk#72]
I'm using the SDK to create a database backup configuration, and it returns no data because of an error. However, the configuration backup is created on Forge Panel.

```
[2020-06-19 17:59:28] local.ERROR: array_map(): Expected parameter 2 to be an array, null given {"exception":"[object] (ErrorException(code: 0): array_map(): Expected parameter 2 to be an array, null given at /Sites/vendor/themsaid/forge-sdk/src/Resources/Resource.php:80)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_map(): Ex...', '/Sites...', 80, Array)
#1 /Sites/vendor/themsaid/forge-sdk/src/Resources/Resource.php(80): array_map(Object(Closure), NULL)
#2 /Sites/vendor/themsaid/forge-sdk/src/Resources/BackupConfiguration.php(92): Themsaid\\Forge\\Resources\\Resource->transformCollection(NULL, 'Themsaid\\\\Forge\\\\...', Array)
#3 /Sites/vendor/themsaid/forge-sdk/src/Actions/ManagesBackups.php(51): Themsaid\\Forge\\Resources\\BackupConfiguration->__construct(Array, Object(Themsaid\\Forge\\Forge))
#4 /Sites/app/Jobs/Master/Domains/Database/SetupForgeBackup.php(91): Themsaid\\Forge\\Forge->createBackupConfiguration('(reserved)', Array)
#5 [internal function]: App\\Jobs\\Master\\Domains\\Database\\SetupForgeBackup->handle()
```

Any idea?

**Comment by driesvints** [comment]
Fixed on master

**Comment by masterix21** [comment]
Thank you
